version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    volumes:
      - ./:/var/lib/postgresql/data

  backend:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '3000:3000'
    depends_on:
      - db